{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.denyAll }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "rasa-common.names.fullname" . }}-deny-all
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  - Egress
{{- end }}
