{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rasa-common.names.fullname" . }}-rasa-allow-egress-http-https
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rasa
  policyTypes:
  - Egress
  egress:
  - ports:
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 80
{{- end }}
