{{- if and .Values.nginx.enabled .Values.nginx.tls.enabled .Values.nginx.tls.generateSelfSignedCert  }}
{{- $cert := genSelfSignedCertWithKey (include "rasa-common.names.fullname" .) nil nil 365 (genPrivateKey "rsa") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rasa-common.names.fullname" . }}-nginx-tls
  labels:
    {{- include "rasa-common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  cert.pem: {{ $cert.Cert | b64enc | quote }}
  key.pem: {{ $cert.Key | b64enc | quote }}
{{- end }}
