annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: update rasa-action-server chart version/dependency
apiVersion: v2
appVersion: 3.2.6
dependencies:
- name: rasa-common
  repository: https://helm.rasa.com
  tags:
  - rasa-common
  version: ~1.0.2
- condition: postgresql.install
  name: postgresql
  repository: oci://europe-west3-docker.pkg.dev/rasa-releases/rasa-x-helm
  version: 10.16.2
- condition: redis.install
  name: redis
  repository: oci://europe-west3-docker.pkg.dev/rasa-releases/rasa-x-helm
  version: 15.7.6
- condition: rabbitmq.install
  name: rabbitmq
  repository: oci://europe-west3-docker.pkg.dev/rasa-releases/rasa-x-helm
  version: 8.32.2
- condition: rasa-action-server.install
  name: rasa-action-server
  repository: https://helm.rasa.com
  version: ~1.0.4
- condition: duckling.install
  name: duckling
  repository: https://helm.rasa.com
  version: ~1.1.4
description: The Rasa Helm chart deploy a Rasa Open Source Server. Rasa is an open
  source machine learning framework for automated text and voice-based conversations.
icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqZPsa-h0ilYPCFaQmf21MFMyVH7oyvrfnJHwvGOJVlMIeTiakBJTSwGd2cDFcF5AsEiY&usqp=CAU
keywords:
- kubernetes
- rasa
- rasa-oss
maintainers:
- email: hi@rasa.com
  name: Rasa
name: rasa
sources:
- https://github.com/RasaHQ/helm-charts/tree/main/charts/rasa
type: application
version: 1.17.6
